### ISSUE TITLE
Add Stale configuration

### ISSUE THREAD

**Issue by aldesantis** [solidusio-contrib/solidus_extension_dev_tools#21]
We have installed [Stale](https://github.com/apps/stale) in the `solidusio-contrib` GitHub organization. To configure it properly, we should add the following to all extensions and also to the extension template as `.github/stale.yml`:

```yaml
# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
```

## To do 

- [ ] Add this configuration in all extensions
- [ ] Add the configuration in solidus extensions dev tools gem generator
