### ISSUE TITLE
Configure RuboCop excluded files automatically

### ISSUE THREAD

**Issue by aldesantis** [solidusio-contrib/solidus_extension_dev_tools#4]
Currently, we ask users to copy-paste the following RuboCop configuration into their extension to leverage our centralized config:

```yaml
require:
  - solidus_extension_dev_tools/rubocop

inherit_gem:
  solidus_extension_dev_tools: .rubocop.extension.yml

AllCops:
  Exclude:
    - spec/dummy/**/*
    - vendor/**/*
```

The reason the `Exclude` directive is there rather than in our own configuration is that RuboCop doesn't seem to inherit it when using `inherit_gem`.

With that said, I'm sure we can somehow inject the configuration into RuboCop via the `require` statement (i.e. by adding something to `solidus_extension_dev_tools/rubocop`). RuboCop's own extension [do something similar](https://github.com/rubocop-hq/rubocop-performance/blob/master/lib/rubocop/performance/inject.rb), so I'm pretty confident.
